version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store:
